-- KOSH ONLY: sqrhwxjgyuqmjsclgmvt. Never apply to Platform bpvbnxqtfwrsmrpvcepc.
-- Prepared locally. No hosted migration is authorized by this file.
-- Filename generated by the Supabase CLI in an isolated /tmp project.
begin;
create schema if not exists kosh;
create schema if not exists kosh_private;
revoke all on schema kosh_private from public, anon;
grant usage on schema kosh, kosh_private to authenticated;

create table if not exists kosh.artifacts (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  kind text not null default 'skill' check (kind = 'skill'),
  title text not null check (length(trim(title)) between 1 and 100),
  latest_revision integer not null default 0 check (latest_revision >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(id, owner_id)
);
create index if not exists artifacts_owner_updated on kosh.artifacts(owner_id, updated_at desc);
create table if not exists kosh.artifact_versions (
  artifact_id uuid not null,
  owner_id uuid not null,
  revision integer not null check (revision > 0),
  snapshot jsonb not null check (octet_length(snapshot::text) <= 65536),
  content_digest text not null check (content_digest ~ '^[0-9a-f]{64}$'),
  created_at timestamptz not null default now(),
  primary key(artifact_id, revision),
  unique(artifact_id, revision, owner_id, content_digest),
  foreign key(artifact_id, owner_id) references kosh.artifacts(id, owner_id) on delete cascade
);
create table if not exists kosh.artifact_test_results (
  id uuid primary key default gen_random_uuid(),
  artifact_id uuid not null,
  revision integer not null,
  owner_id uuid not null,
  content_digest text not null,
  sample_digest text not null check (sample_digest ~ '^[0-9a-f]{64}$'),
  sample jsonb not null check (octet_length(sample::text) <= 40000),
  assessments jsonb not null,
  created_at timestamptz not null default now(),
  foreign key(artifact_id, revision, owner_id, content_digest)
    references kosh.artifact_versions(artifact_id, revision, owner_id, content_digest) on delete cascade
);
create index if not exists artifact_results_owner on kosh.artifact_test_results(owner_id, artifact_id);

alter table kosh.artifacts enable row level security;
alter table kosh.artifact_versions enable row level security;
alter table kosh.artifact_test_results enable row level security;
revoke all on kosh.artifacts, kosh.artifact_versions, kosh.artifact_test_results from public, anon, authenticated;
grant select on kosh.artifacts, kosh.artifact_versions, kosh.artifact_test_results to authenticated;
drop policy if exists artifacts_read_owner on kosh.artifacts;
create policy artifacts_read_owner on kosh.artifacts for select to authenticated using ((select auth.uid()) = owner_id);
drop policy if exists versions_read_owner on kosh.artifact_versions;
create policy versions_read_owner on kosh.artifact_versions for select to authenticated using ((select auth.uid()) = owner_id);
drop policy if exists results_read_owner on kosh.artifact_test_results;
create policy results_read_owner on kosh.artifact_test_results for select to authenticated using ((select auth.uid()) = owner_id);

-- Stable JSON matches the application for its ASCII-keyed schema. No caller-supplied digest is trusted.
create or replace function kosh_private.canonical_json(value jsonb) returns text
language sql immutable strict set search_path = '' as $$
  select case jsonb_typeof(value)
    when 'object' then '{' || coalesce((select string_agg(to_jsonb(key)::text || ':' || kosh_private.canonical_json(v), ',' order by key collate "C") from jsonb_each(value) as e(key,v)), '') || '}'
    when 'array' then '[' || coalesce((select string_agg(kosh_private.canonical_json(v), ',' order by ordinal) from jsonb_array_elements(value) with ordinality as a(v,ordinal)), '') || ']'
    else value::text end;
$$;
revoke all on function kosh_private.canonical_json(jsonb) from public, anon;
grant execute on function kosh_private.canonical_json(jsonb) to authenticated;

-- Write authority is restricted to these narrow transactions. The private definer is
-- required because clients deliberately cannot insert/update immutable version rows.
create or replace function kosh_private.save_artifact(p_snapshot jsonb, p_id uuid, p_expected integer)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare actor uuid := auth.uid(); item kosh.artifacts%rowtype; next_revision integer; hash text; field text;
begin
  if actor is null then raise sqlstate '42501' using message = 'Sign in to save a version.'; end if;
  if p_expected is null or p_expected < 0 or p_snapshot is null or octet_length(p_snapshot::text) > 65536
    or (p_snapshot->>'schemaVersion' = '1' and p_snapshot->>'kind' = 'skill'
      and p_snapshot->'dependencies' = '[]'::jsonb
      and p_snapshot#>>'{governance,enforcement}' = 'instruction-only'
      and jsonb_typeof(p_snapshot->'content') = 'object'
      and jsonb_typeof(p_snapshot#>'{content,inputs}') = 'array'
      and jsonb_typeof(p_snapshot#>'{content,steps}') = 'array'
      and length(trim(p_snapshot->>'title')) between 1 and 100
      and length(p_snapshot->>'slug') between 1 and 64
      and p_snapshot->>'slug' ~ '^[a-z0-9]+(-[a-z0-9]+)*$') is not true
    or exists(select 1 from jsonb_object_keys(p_snapshot) as k where k not in ('schemaVersion','kind','title','slug','summary','content','governance','source','dependencies'))
  then raise sqlstate '22023' using message = 'Invalid skill snapshot.'; end if;
  foreach field in array array['purpose','useWhen','output','qualityChecks','limitations'] loop
    if jsonb_typeof(p_snapshot->'content'->field) is distinct from 'string' then raise sqlstate '22023' using message = 'Invalid skill content.'; end if;
  end loop;
  if p_id is null then
    if p_expected <> 0 then raise sqlstate '40001' using message = 'A new artifact starts at revision zero.'; end if;
    insert into kosh.artifacts(owner_id,title) values(actor,p_snapshot->>'title') returning * into item;
  else
    select * into item from kosh.artifacts where id = p_id and owner_id = actor for update;
    if not found then raise sqlstate 'P0002' using message = 'Artifact unavailable.'; end if;
    if item.latest_revision <> p_expected then raise sqlstate '40001' using message = 'A newer version exists. Compare before saving.'; end if;
  end if;
  next_revision := item.latest_revision + 1;
  hash := encode(sha256(convert_to(kosh_private.canonical_json(p_snapshot),'UTF8')),'hex');
  insert into kosh.artifact_versions(artifact_id,owner_id,revision,snapshot,content_digest)
    values(item.id,actor,next_revision,p_snapshot,hash);
  update kosh.artifacts set latest_revision = next_revision, title = p_snapshot->>'title', updated_at = now() where id = item.id;
  return jsonb_build_object('id',item.id,'revision',next_revision,'contentDigest',hash,'updatedAt',now());
end;
$$;
revoke all on function kosh_private.save_artifact(jsonb,uuid,integer) from public, anon;
grant execute on function kosh_private.save_artifact(jsonb,uuid,integer) to authenticated;
create or replace function kosh.save_artifact(p_snapshot jsonb, p_id uuid default null, p_expected integer default 0)
returns jsonb language sql security invoker set search_path = '' as $$ select kosh_private.save_artifact(p_snapshot,p_id,p_expected); $$;
revoke all on function kosh.save_artifact(jsonb,uuid,integer) from public, anon;
grant execute on function kosh.save_artifact(jsonb,uuid,integer) to authenticated;

create or replace function kosh_private.delete_artifact(p_id uuid, p_expected integer)
returns boolean language plpgsql security definer set search_path = '' as $$
declare item kosh.artifacts%rowtype;
begin
  if auth.uid() is null then raise sqlstate '42501' using message = 'Sign in required.'; end if;
  select * into item from kosh.artifacts where id = p_id and owner_id = auth.uid() for update;
  if not found then raise sqlstate 'P0002' using message = 'Artifact unavailable.'; end if;
  if p_expected is null or item.latest_revision <> p_expected then raise sqlstate '40001' using message = 'Artifact changed. Review it before deleting.'; end if;
  delete from kosh.artifacts where id = item.id;
  return true;
end;
$$;
revoke all on function kosh_private.delete_artifact(uuid,integer) from public, anon;
grant execute on function kosh_private.delete_artifact(uuid,integer) to authenticated;
create or replace function kosh.delete_artifact(p_id uuid, p_expected integer) returns boolean
language sql security invoker set search_path = '' as $$ select kosh_private.delete_artifact(p_id,p_expected); $$;
revoke all on function kosh.delete_artifact(uuid,integer) from public, anon;
grant execute on function kosh.delete_artifact(uuid,integer) to authenticated;

create or replace function kosh_private.save_test_evidence(p_id uuid, p_revision integer, p_digest text, p_sample jsonb, p_assessments jsonb)
returns uuid language plpgsql security definer set search_path = '' as $$
declare actor uuid := auth.uid(); result_id uuid; field text;
begin
  if actor is null then raise sqlstate '42501' using message = 'Sign in required.'; end if;
  if not exists(select 1 from kosh.artifact_versions where artifact_id=p_id and revision=p_revision and owner_id=actor and content_digest=p_digest) then raise sqlstate 'P0002' using message = 'Matching saved version unavailable.'; end if;
  if p_sample is null or p_assessments is null or octet_length(p_sample::text)>40000 then raise sqlstate '22023' using message='Invalid test evidence.'; end if;
  foreach field in array array['name','input','expected','disallowed','output'] loop
    if jsonb_typeof(p_sample->field) is distinct from 'string' or length(trim(p_sample->>field))=0 then raise sqlstate '22023' using message='Complete the sample before saving evidence.'; end if;
  end loop;
  foreach field in array array['output','evidence','boundaries'] loop
    if (p_assessments->>field in ('pass','fail','needs-review')) is not true then raise sqlstate '22023' using message='Invalid human assessment.'; end if;
  end loop;
  if exists(select 1 from jsonb_object_keys(p_sample) as k where k not in ('name','input','expected','disallowed','output')) or exists(select 1 from jsonb_object_keys(p_assessments) as k where k not in ('output','evidence','boundaries')) then raise sqlstate '22023' using message='Unexpected evidence fields.'; end if;
  insert into kosh.artifact_test_results(artifact_id,revision,owner_id,content_digest,sample_digest,sample,assessments)
    values(p_id,p_revision,actor,p_digest,encode(sha256(convert_to(kosh_private.canonical_json(p_sample),'UTF8')),'hex'),p_sample,p_assessments) returning id into result_id;
  return result_id;
end;
$$;
revoke all on function kosh_private.save_test_evidence(uuid,integer,text,jsonb,jsonb) from public, anon;
grant execute on function kosh_private.save_test_evidence(uuid,integer,text,jsonb,jsonb) to authenticated;
create or replace function kosh.save_test_evidence(p_id uuid,p_revision integer,p_digest text,p_sample jsonb,p_assessments jsonb) returns uuid
language sql security invoker set search_path = '' as $$ select kosh_private.save_test_evidence(p_id,p_revision,p_digest,p_sample,p_assessments); $$;
revoke all on function kosh.save_test_evidence(uuid,integer,text,jsonb,jsonb) from public, anon;
grant execute on function kosh.save_test_evidence(uuid,integer,text,jsonb,jsonb) to authenticated;

-- Withdrawal is an explicit owner action. A result cannot be altered into different evidence.
create or replace function kosh_private.remove_test_evidence(p_id uuid) returns boolean
language plpgsql security definer set search_path = '' as $$
begin
  if auth.uid() is null then raise sqlstate '42501' using message = 'Sign in required.'; end if;
  delete from kosh.artifact_test_results where id=p_id and owner_id=auth.uid();
  return found;
end;
$$;
revoke all on function kosh_private.remove_test_evidence(uuid) from public, anon;
grant execute on function kosh_private.remove_test_evidence(uuid) to authenticated;
create or replace function kosh.remove_test_evidence(p_id uuid) returns boolean
language sql security invoker set search_path = '' as $$ select kosh_private.remove_test_evidence(p_id); $$;
revoke all on function kosh.remove_test_evidence(uuid) from public, anon;
grant execute on function kosh.remove_test_evidence(uuid) to authenticated;
commit;
